#!/usr/bin/env bash
# vim:ft=sh:ts=2:sts=2:sw=2:et

set -e

#
# Arguments
#

if [[ -z "${1}" ]]; then
  echo "usage: ${0} <client-name>"
  exit 1
fi

#
# Variables
#

script_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
client_name="${1}"
easyrsa_path="${script_path}/../easy-rsa"
server_path="${script_path}/../server"
client_path="${script_path}/../client"

#
# Create directories
#

mkdir -p "${client_path}"
mkdir -p "${server_path}/ccd"

#
# Figure out client IP address
#

client_ip="$(grep -R 'ifconfig-push' "${server_path}/ccd" | awk '{ print $2 }' | sort -rV | head -1)"
client_ip="${client_ip:-10.8.0.1}"
echo "${client_ip}"
IFS='.' read -ra client_ip_arr <<< "${client_ip}"
client_ip_arr[3]=$(( client_ip_arr[3]+1 ))
client_ip="${client_ip_arr[0]}.${client_ip_arr[1]}.${client_ip_arr[2]}.${client_ip_arr[3]}"

#
# Issue certificates
#

"${easyrsa_path}/easyrsa" build-client-full "${client_name}" nopass

#
# Create OpenVPN embedded config
#

{
  cat "${server_path}/client.conf"

  echo '# ca.crt'
  echo '<ca>'
  cat "${easyrsa_path}/pki/ca.crt"
  echo '</ca>'

  echo '# client.crt'
  echo '<cert>'
  cat "${easyrsa_path}/pki/issued/${client_name}.crt"
  echo '</cert>'

  echo '# client.key'
  echo '<key>'
  cat "${easyrsa_path}/pki/private/${client_name}.key"
  echo '</key>'

  echo '# ta.key'
  echo '<tls-auth>'
  cat "${easyrsa_path}/pki/ta.key"
  echo '</tls-auth>'
} > "${client_path}/${client_name}.ovpn"

#
# Create OpenVPN CCD file for static IP assignment
#

echo "ifconfig-push ${client_ip} 255.255.255.0" >>"${server_path}/ccd/${client_name}"
