#!/usr/bin/env bash
# vim:ft=sh:ts=2:sts=2:sw=2:et

set -e

#
# Arguments
#

if [[ -z "${1}" ]]; then
  echo "usage: ${0} <client-name>"
  exit 1
fi

#
# Variables
#

script_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root_path="$(cd "${script_path}/.." && pwd)"
easyrsa_path="${root_path}/easyrsa"
pki_path="${root_path}/pki"
server_path="${root_path}/server"
client_path="${root_path}/client"

client_name="${1}"

#
# Create directories
#

mkdir -p "${pki_path}/tmp"

#
# Revoke certificates
#

"${easyrsa_path}/easyrsa" --pki-dir="${pki_path}" revoke "${client_name}"

#
# Update revocation list
#

"${easyrsa_path}/easyrsa" --pki-dir="${pki_path}" gen-crl

#
# Remove leftovers
#

rm "${server_path}/ccd/${client_name}" "${client_path}/${client_name}.ovpn"
