#!/usr/bin/env bash
# vim:ft=sh:ts=2:sts=2:sw=2:et

if [ -z "${EASYRSA_CALLER}" ]; then
  echo "You appear to be sourcing an Easy-RSA 'vars' file." >&2
  echo "This is no longer necessary and is disallowed. See the section called" >&2
  echo "'How to use this file' near the top comments for more details." >&2
  return 1
fi

ROOT="${BASH_SOURCE[0]%/*/*}"

set_var EASYRSA                 "${ROOT}/easyrsa"
set_var EASYRSA_OPENSSL         "openssl"
set_var EASYRSA_PKI             "${ROOT}/pki"
set_var EASYRSA_TEMP_DIR        "${EASYRSA_PKI}/tmp"

set_var EASYRSA_REQ_COUNTRY     "US"
set_var EASYRSA_REQ_PROVINCE    "California"
set_var EASYRSA_REQ_CITY        "San Francisco"
set_var EASYRSA_REQ_ORG         "Copyleft Certificate Co"
set_var EASYRSA_REQ_EMAIL       "root@example.org"
set_var EASYRSA_REQ_OU          "Wednesday, Thursday, Friday"

set_var EASYRSA_KEY_SIZE        4096
set_var EASYRSA_ALGO            rsa
set_var EASYRSA_CURVE           secp384r1
set_var EASYRSA_CA_EXPIRE       3650
set_var EASYRSA_CERT_EXPIRE     3650
set_var EASYRSA_CRL_DAYS        3650
